# Generated by Django 5.2.3 on 2026-06-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_db_path', models.CharField(blank=True, max_length=500)),
                ('access_db_password_enc', models.CharField(blank=True, max_length=500)),
                ('pg_host', models.CharField(blank=True, default='localhost', max_length=255)),
                ('pg_port', models.IntegerField(default=5432)),
                ('pg_dbname', models.CharField(blank=True, max_length=255)),
                ('pg_user', models.CharField(blank=True, max_length=255)),
                ('pg_password_enc', models.CharField(blank=True, max_length=500)),
                ('pg_sslmode', models.CharField(default='prefer', max_length=20)),
                ('web_to_access_enabled', models.BooleanField(default=True)),
                ('access_to_web_enabled', models.BooleanField(default=False)),
                ('dry_run', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=15)),
                ('cron_expr', models.CharField(blank=True, help_text='optional 5-field cron; overrides interval', max_length=120)),
                ('scheduler_paused', models.BooleanField(default=False)),
                ('state_dir', models.CharField(blank=True, max_length=500)),
                ('outbound_cursor', models.CharField(blank=True, max_length=120)),
                ('inbound_cursor', models.CharField(blank=True, max_length=120)),
                ('alerts_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=255)),
                ('smtp_password_enc', models.CharField(blank=True, max_length=500)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('alert_from', models.CharField(blank=True, max_length=255)),
                ('alert_recipients', models.CharField(blank=True, help_text='comma-separated', max_length=1000)),
            ],
            options={
                'verbose_name': 'Agent settings',
                'verbose_name_plural': 'Agent settings',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trigger', models.CharField(default='manual', max_length=20)),
                ('direction', models.CharField(default='web2access', max_length=12)),
                ('status', models.CharField(default='ok', max_length=12)),
                ('tables_processed', models.IntegerField(default=0)),
                ('rows_written', models.IntegerField(default=0)),
                ('cursor', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('web2access', 'web -> access'), ('access2web', 'access -> web')], default='web2access', max_length=12)),
                ('access_table', models.CharField(max_length=255)),
                ('pg_table', models.CharField(blank=True, help_text='CRM PostgreSQL table', max_length=255)),
                ('web_entity', models.CharField(blank=True, max_length=255)),
                ('key_column', models.CharField(help_text='Access key column', max_length=255)),
                ('conflict_rule', models.CharField(choices=[('web-wins', 'web-wins'), ('newest-wins', 'newest-wins')], default='web-wins', max_length=12)),
                ('cursor_column', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['order', 'access_table'],
                'unique_together': {('direction', 'access_table')},
            },
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_column', models.CharField(max_length=255)),
                ('crm_field', models.CharField(help_text='PostgreSQL column', max_length=255)),
                ('data_type', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('key', 'key'), ('sync', 'sync'), ('no', 'no (never leaves source)'), ('review', 'review (pending sign-off)'), ('candidate', 'candidate (inbound)')], default='sync', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='syncadmin.tablemapping')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('table', 'access_column')},
            },
        ),
    ]
