# Generated by Django 5.2.3 on 2026-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='traceback',
            field=models.TextField(blank=True),
        ),
    ]
