# Generated by Django 5.2.3 on 2026-07-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncadmin', '0002_syncrun_traceback'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='value_map',
            field=models.TextField(blank=True),
        ),
    ]
