# Generated by Django 5.2.3 on 2026-08-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncadmin', '0003_fieldmapping_value_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmapping',
            name='role',
            field=models.CharField(choices=[('key', 'key'), ('sync', 'sync'), ('no', 'no (never leaves source)'), ('review', 'review (pending sign-off)'), ('candidate', 'candidate (inbound)'), ('match', 'match (natural-key resolution)')], default='sync', max_length=12),
        ),
    ]
