# Generated by Django 5.2.3 on 2026-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncadmin', '0004_alter_fieldmapping_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='backup_keep',
            field=models.PositiveIntegerField(default=10, help_text='max backups to keep per Access file (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='backup_min_interval_minutes',
            field=models.PositiveIntegerField(default=0, help_text='minimum minutes between backups (0 = back up every write)'),
        ),
    ]
