# Generated by Django 5.2.3 on 2026-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncadmin', '0005_agentsettings_backup_keep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='alert_throttle_minutes',
            field=models.PositiveIntegerField(default=60, help_text='minimum minutes between alert emails (anti-spam; 0 = no throttle)'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='health_stale_minutes',
            field=models.PositiveIntegerField(default=90, help_text='alert if no successful sync within this many minutes'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='last_alert_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
